spring:
  datasource: # 2 espaços de recuo
    url: "jdbc:postgresql://localhost:5432/bancodigital_db" # 4 espaços
    username: postgres
    password: ${DB_PASSWORD:Admin}
    driver-class-name: org.postgresql.Driver